# ./.rubocop.yml
require:
  - "anycable/rails/compatibility/rubocop"

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 100
  Exclude:
    - ./db/seeds.rb
    - ./config/initializers/*.rb

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*_spec.rb
    - ./lib/tasks/*.rake

Metrics/MethodLength:
  Exclude:
    - ./db/migrate/*.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - ./spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - ./db/seeds.rb

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Max: 20
